name: publish-release

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.create_tag.outputs.version }}
    strategy:
      matrix:
        python-version: ['3.13']
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          pip install uv
          uv sync

      - name: run python
        run: |
          uv run ntfsdump -h
      
      - name: build
        run: |
          uv run python -m nuitka \
            --standalone \
            --onefile \
            --follow-imports \
            --include-distribution-metadata=ntfsdump \
            -o ntfsdump.exe \
            --output-dir=dist \
            --assume-yes-for-downloads \
            src/ntfsdump/cli.py

      
      - name: verify
        run: |
          dist/ntfsdump.exe -h
          dist/ntfsdump.exe --version
      
      - name: create tag
        id: create_tag
        if: startsWith(github.ref, 'refs/heads/master')
        run: |
          version=$(grep '__version__' src/ntfsdump/__about__.py | awk -F '"' '{print $2}')
          git tag "v$version"
          git push origin "v$version"
          echo "version=v$version" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create_tag.outputs.version }}
          files: dist/ntfsdump.exe
          name: Release ${{ steps.create_tag.outputs.version }}
          body: 'This release was automatically created by GitHub Actions.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    needs: build-windows
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.13']
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      


      - name: Install dependencies
        run: |
          sudo apt install patchelf
          pip install uv
          uv sync

      - name: run python
        run: |
          uv run ntfsdump -h

      - name: build
        run: |
          uv run python -m nuitka \
            --standalone \
            --onefile \
            --follow-imports \
            --include-distribution-metadata=ntfsdump \
            -o ntfsdump \
            --output-dir=dist \
            --assume-yes-for-downloads \
            src/ntfsdump/cli.py
      
      - name: verify
        run: |
          dist/ntfsdump -h
          dist/ntfsdump --version

      - name: upload asset to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.build-windows.outputs.version }}
          files: dist/ntfsdump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
